### ISSUE TITLE
Do we really need npm?

### ISSUE THREAD

**Issue by cryptapus** [myriadteam/myriadteam.github.io#114]
Perhaps we can move to a static html/css/js site?

I have a version prepared long ago:

https://github.com/cryptapus/myriadteam.github.io

edit: if considered, I will update and submit a proper pull request

**Comment by 8bitcoder** [comment]
I would also prefer a static site.

**Comment by cryptapus** [comment]
submitted proposal in #118

**Comment by cryptapus** [comment]
also, if this proves to be useful, I will propose to change this repo to myriadteam.github.io for real-time testing on github pages.

**Comment by cryptapus** [comment]
Since this appears to work now I'll plan a repo name change wk1851 unless there are any objections.

**Comment by cryptapus** [comment]
Completed.
