### ISSUE TITLE
arabic & farsi script does not display and reverts to english

### ISSUE THREAD

**Issue by myriadcoiner** [myriadteam/myriadteam.github.io#126]

**Comment by 8bitcoder** [comment]
I had a look at arabic/farsi, couldn't immediately see something wrong. Sometimes a misplaced comma or quote can break it.

**Comment by 8bitcoder** [comment]
These farsi linges has an extra comma at the end of the list, not sure if javascript allows that.

 'wallets-desktop-windows': {
    'eo': "Vindozo"
    'eo': "Vindozo",
    'fa': "ویندوز",
  },
  'wallets-desktop-x86-installer': {
    'eo': "32-bit instalilo"
    'eo': "32-bit instalilo",
    'fa': "برنامه نصب ۳۲ بیتی",
  },
  'wallets-desktop-x64-installer': {
    'eo': "64-bit instalilo"
    'eo': "64-bit instalilo",
    'fa': "برنامه نصب ۶۴ بیتی",
  },
  'wallets-desktop-other': {
    'eo': "Aliaj duumaj dosieroj"
    'eo': "Aliaj duumaj dosieroj",
    'fa': "سایر برنامه‌ها",
  },
  'wallets-desktop-github': {
    'eo': "Vidi ĉe GitHub"
    'eo': "Vidi ĉe GitHub",
    'fa': "مشاهده در گیت‌هاب",
  },

**Comment by myriadcoiner** [comment]
thanks. fixed farsi, still haven't found the bug for arabic

**Comment by 8bitcoder** [comment]
This commit should fix it:

https://github.com/myriadteam/myriadteam.github.io/commit/6c85ab24eba1c91c4f415f7d2f899a0e60eea0b4
