### ISSUE TITLE
Dove Wallet on Myriad official page

### ISSUE THREAD

**Issue by 007JAC** [myriadteam/myriadteam.github.io#150]
Hi,

Dove Wallet is the easiest service to deposit, transfer, trade Myriadcoin. 
We hope anyone enjoys their financial life anywhere, anytime. I write a request about listing Dove Wallet on Myriad official exchange page. 

This is our service link below.

Dove Wallet
https://dovewallet.com

![Dove_Wallet_official_logo](https://user-images.githubusercontent.com/36462701/61933934-9d34dd80-af76-11e9-8ae3-21885e082e94.png)

Thanks!

**Comment by cryptapus** [comment]
Addressed in #152

**Comment by 007JAC** [comment]
Hi,

Thank you for the listing! 😊

2019년 8월 2일 (금) 오후 2:32, cryptapus <notifications@github.com>님이 작성:
