### ISSUE TITLE
New website update for Members page, Road map and the Merchant page

### ISSUE THREAD

**Issue by caveout** [myriadteam/myriadteam.github.io#154]
i uploaded a zip file at: 

https://github.com/caveout/myriadteam.github.io/blob/caveout-patch-1/myriad.zip

for the new website update, if someone wants to look though it, make changes  and update the main website.

this is my first time using Github so i don't know how it works

**Comment by cryptapus** [comment]
Try "New pull request" in your repo, and target this repo to create a Pull Request. That should get you started.

**Comment by cryptapus** [comment]
You seem to have the hang of it in #155. You can keep editing your branch with more commits and they will be included if the PR is merged. There's a lot there, so we'll need some consensus with the other devs and contributors so please be patient.

**Comment by caveout** [comment]
> You seem to have the hang of it in #155. You can keep editing your branch with more commits and they will be included if the PR is merged. There's a lot there, so we'll need some consensus with the other devs and contributors so please be patient.

no problem, yep it be great for others to see, agree and improve it.
