### ISSUE TITLE
Issue: Why myriad? video is private

### ISSUE THREAD

**Issue by veloki** [myriadteam/myriadteam.github.io#165]
https://youtu.be/Hlmh_1RczNE

This video is private we should remove it or the owner make it public

**Comment by veloki** [comment]
we can use this one https://www.youtube.com/watch?v=JWfxr5cQJug or if someone wants to make a new one

**Comment by veloki** [comment]
#166 update done

**Comment by cryptapus** [comment]
Hmm... #166 doesn't seem to work, so I'll revert in #167.

**Comment by veloki** [comment]
check this: https://stackoverflow.com/questions/17799596/embedding-youtube-videos-doesnt-work-in-local-html-files-using-file-url

**Comment by cryptapus** [comment]
not sure... but I'll revert my revert and maybe you can see... Maybe it was just my browser?

**Comment by veloki** [comment]
not sure we can check, if not we revert again and i'll search for a solution

**Comment by veloki** [comment]
i have created a new pull request for tracking better

**Comment by veloki** [comment]
Fixed on master branch
